<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolePrivilegeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $aryRolePrivileges = [
            ['roleID' => '1','privilegeID' => '1'],
            ['roleID' => '1','privilegeID' => '2'],
            ['roleID' => '1','privilegeID' => '3'],
            ['roleID' => '1','privilegeID' => '4'],
            ['roleID' => '1','privilegeID' => '5'],
            ['roleID' => '1','privilegeID' => '6'],
            ['roleID' => '1','privilegeID' => '7'],
            ['roleID' => '1','privilegeID' => '8'],
            ['roleID' => '1','privilegeID' => '9'],
            ['roleID' => '1','privilegeID' => '10'],
            ['roleID' => '1','privilegeID' => '11'],
            ['roleID' => '1','privilegeID' => '12'],
            ['roleID' => '1','privilegeID' => '13'],
            ['roleID' => '1','privilegeID' => '14'],
            ['roleID' => '1','privilegeID' => '15'],
            ['roleID' => '1','privilegeID' => '16'],
            ['roleID' => '1','privilegeID' => '17'],
            ['roleID' => '1','privilegeID' => '18'],
            ['roleID' => '1','privilegeID' => '19'],
            ['roleID' => '1','privilegeID' => '20'],
            ['roleID' => '1','privilegeID' => '21'],
            ['roleID' => '1','privilegeID' => '22'],
            ['roleID' => '1','privilegeID' => '23'],
            ['roleID' => '1','privilegeID' => '24'],
            ['roleID' => '1','privilegeID' => '25'],
            ['roleID' => '1','privilegeID' => '26'],
            ['roleID' => '1','privilegeID' => '27'],
            ['roleID' => '1','privilegeID' => '28'],
            ['roleID' => '1','privilegeID' => '29'],
            ['roleID' => '1','privilegeID' => '30'],
            ['roleID' => '1','privilegeID' => '31'],
            ['roleID' => '1','privilegeID' => '32'],
            ['roleID' => '1','privilegeID' => '33'],
            ['roleID' => '1','privilegeID' => '34'],
            ['roleID' => '1','privilegeID' => '35'],
            ['roleID' => '1','privilegeID' => '36'],
            ['roleID' => '1','privilegeID' => '37'],
            ['roleID' => '1','privilegeID' => '38'],
            ['roleID' => '1','privilegeID' => '39'],
            ['roleID' => '1','privilegeID' => '40'],
            ['roleID' => '1','privilegeID' => '41'],
            ['roleID' => '1','privilegeID' => '42'],
            ['roleID' => '1','privilegeID' => '43'],
            ['roleID' => '1','privilegeID' => '44'],
            ['roleID' => '1','privilegeID' => '45'],
            ['roleID' => '1','privilegeID' => '46'],
            ['roleID' => '1','privilegeID' => '47'],
            ['roleID' => '1','privilegeID' => '48'],
            ['roleID' => '1','privilegeID' => '49'],
            ['roleID' => '1','privilegeID' => '50'],
            ['roleID' => '1','privilegeID' => '51'],
            ['roleID' => '1','privilegeID' => '52'],
            ['roleID' => '1','privilegeID' => '53'],
            ['roleID' => '1','privilegeID' => '54'],
            ['roleID' => '1','privilegeID' => '55'],
            ['roleID' => '1','privilegeID' => '56'],
            ['roleID' => '1','privilegeID' => '57'],
            ['roleID' => '1','privilegeID' => '58'],
            ['roleID' => '1','privilegeID' => '59'],
            ['roleID' => '1','privilegeID' => '60'],
            ['roleID' => '2','privilegeID' => '22'],
            ['roleID' => '2','privilegeID' => '26'],
            ['roleID' => '2','privilegeID' => '30'],
            ['roleID' => '2','privilegeID' => '34'],
            ['roleID' => '2','privilegeID' => '38'],
            ['roleID' => '2','privilegeID' => '42'],
            ['roleID' => '2','privilegeID' => '45'],
            ['roleID' => '2','privilegeID' => '46'],
            ['roleID' => '2','privilegeID' => '47'],
            ['roleID' => '2','privilegeID' => '48'],
            ['roleID' => '2','privilegeID' => '49'],
            ['roleID' => '2','privilegeID' => '50'],
            ['roleID' => '2','privilegeID' => '51'],
            ['roleID' => '2','privilegeID' => '52'],
            ['roleID' => '2','privilegeID' => '58'],
            ['roleID' => '3','privilegeID' => '22'],
            ['roleID' => '3','privilegeID' => '26'],
            ['roleID' => '3','privilegeID' => '30'],
            ['roleID' => '3','privilegeID' => '34'],
            ['roleID' => '3','privilegeID' => '38'],
            ['roleID' => '3','privilegeID' => '42'],
            ['roleID' => '3','privilegeID' => '45'],
            ['roleID' => '3','privilegeID' => '46'],
            ['roleID' => '3','privilegeID' => '47'],
            ['roleID' => '3','privilegeID' => '48'],
            ['roleID' => '3','privilegeID' => '49'],
            ['roleID' => '3','privilegeID' => '50'],
            ['roleID' => '3','privilegeID' => '51'],
            ['roleID' => '3','privilegeID' => '52'],
            ['roleID' => '3','privilegeID' => '54'],
            ['roleID' => '3','privilegeID' => '58'],
            ['roleID' => '4','privilegeID' => '22'],
            ['roleID' => '4','privilegeID' => '26'],
            ['roleID' => '4','privilegeID' => '30'],
            ['roleID' => '4','privilegeID' => '34'],
            ['roleID' => '4','privilegeID' => '38'],
            ['roleID' => '4','privilegeID' => '42'],
            ['roleID' => '4','privilegeID' => '45'],
            ['roleID' => '4','privilegeID' => '46'],
            ['roleID' => '4','privilegeID' => '47'],
            ['roleID' => '4','privilegeID' => '48'],
            ['roleID' => '4','privilegeID' => '49'],
            ['roleID' => '4','privilegeID' => '50'],
            ['roleID' => '4','privilegeID' => '51'],
            ['roleID' => '4','privilegeID' => '52'],
            ['roleID' => '4','privilegeID' => '54'],
            ['roleID' => '4','privilegeID' => '58'],
            ['roleID' => '5','privilegeID' => '22'],
            ['roleID' => '5','privilegeID' => '26'],
            ['roleID' => '5','privilegeID' => '30'],
            ['roleID' => '5','privilegeID' => '34'],
            ['roleID' => '5','privilegeID' => '38'],
            ['roleID' => '5','privilegeID' => '42'],
            ['roleID' => '5','privilegeID' => '45'],
            ['roleID' => '5','privilegeID' => '46'],
            ['roleID' => '5','privilegeID' => '47'],
            ['roleID' => '5','privilegeID' => '48'],
            ['roleID' => '5','privilegeID' => '49'],
            ['roleID' => '5','privilegeID' => '50'],
            ['roleID' => '5','privilegeID' => '51'],
            ['roleID' => '5','privilegeID' => '52'],
            ['roleID' => '5','privilegeID' => '54'],
            ['roleID' => '5','privilegeID' => '58'],
            ['roleID' => '6','privilegeID' => '22'],
            ['roleID' => '6','privilegeID' => '45'],
            ['roleID' => '6','privilegeID' => '46'],
            ['roleID' => '6','privilegeID' => '47'],
            ['roleID' => '6','privilegeID' => '48'],
            ['roleID' => '6','privilegeID' => '49'],
            ['roleID' => '6','privilegeID' => '50'],
            ['roleID' => '6','privilegeID' => '51'],
            ['roleID' => '6','privilegeID' => '52'],
            ['roleID' => '6','privilegeID' => '58'],
            ['roleID' => '7','privilegeID' => '22'],
            ['roleID' => '7','privilegeID' => '45'],
            ['roleID' => '7','privilegeID' => '46'],
            ['roleID' => '7','privilegeID' => '47'],
            ['roleID' => '7','privilegeID' => '48'],
            ['roleID' => '7','privilegeID' => '49'],
            ['roleID' => '7','privilegeID' => '50'],
            ['roleID' => '7','privilegeID' => '51'],
            ['roleID' => '7','privilegeID' => '52'],
            ['roleID' => '7','privilegeID' => '58'],
            ['roleID' => '8','privilegeID' => '22'],
            ['roleID' => '8','privilegeID' => '26'],
            ['roleID' => '8','privilegeID' => '30'],
            ['roleID' => '8','privilegeID' => '34'],
            ['roleID' => '8','privilegeID' => '38'],
            ['roleID' => '8','privilegeID' => '42'],
            ['roleID' => '8','privilegeID' => '45'],
            ['roleID' => '8','privilegeID' => '46'],
            ['roleID' => '8','privilegeID' => '47'],
            ['roleID' => '8','privilegeID' => '48'],
            ['roleID' => '8','privilegeID' => '49'],
            ['roleID' => '8','privilegeID' => '50'],
            ['roleID' => '8','privilegeID' => '51'],
            ['roleID' => '8','privilegeID' => '52'],
            ['roleID' => '8','privilegeID' => '58'],
            ['roleID' => '9','privilegeID' => '22'],
            ['roleID' => '9','privilegeID' => '26'],
            ['roleID' => '9','privilegeID' => '30'],
            ['roleID' => '9','privilegeID' => '34'],
            ['roleID' => '9','privilegeID' => '38'],
            ['roleID' => '9','privilegeID' => '42'],
            ['roleID' => '9','privilegeID' => '45'],
            ['roleID' => '9','privilegeID' => '46'],
            ['roleID' => '9','privilegeID' => '47'],
            ['roleID' => '9','privilegeID' => '48'],
            ['roleID' => '9','privilegeID' => '49'],
            ['roleID' => '9','privilegeID' => '50'],
            ['roleID' => '9','privilegeID' => '51'],
            ['roleID' => '9','privilegeID' => '52'],
            ['roleID' => '9','privilegeID' => '58'],
            ['roleID' => '10','privilegeID' => '22'],
            ['roleID' => '10','privilegeID' => '26'],
            ['roleID' => '10','privilegeID' => '30'],
            ['roleID' => '10','privilegeID' => '34'],
            ['roleID' => '10','privilegeID' => '38'],
            ['roleID' => '10','privilegeID' => '42'],
            ['roleID' => '10','privilegeID' => '45'],
            ['roleID' => '10','privilegeID' => '46'],
            ['roleID' => '10','privilegeID' => '47'],
            ['roleID' => '10','privilegeID' => '48'],
            ['roleID' => '10','privilegeID' => '49'],
            ['roleID' => '10','privilegeID' => '50'],
            ['roleID' => '10','privilegeID' => '51'],
            ['roleID' => '10','privilegeID' => '52'],
            ['roleID' => '10','privilegeID' => '58'],
            ['roleID' => '11','privilegeID' => '22'],
            ['roleID' => '11','privilegeID' => '26'],
            ['roleID' => '11','privilegeID' => '30'],
            ['roleID' => '11','privilegeID' => '34'],
            ['roleID' => '11','privilegeID' => '38'],
            ['roleID' => '11','privilegeID' => '42'],
            ['roleID' => '11','privilegeID' => '45'],
            ['roleID' => '11','privilegeID' => '46'],
            ['roleID' => '11','privilegeID' => '47'],
            ['roleID' => '11','privilegeID' => '48'],
            ['roleID' => '11','privilegeID' => '49'],
            ['roleID' => '11','privilegeID' => '50'],
            ['roleID' => '11','privilegeID' => '51'],
            ['roleID' => '11','privilegeID' => '52'],
            ['roleID' => '11','privilegeID' => '58']
        ];

	    foreach ($aryRolePrivileges as $rolePrivilege) {
		    DB::table('rolePrivilege')->insert(
			    [
				    'roleID' => $rolePrivilege['roleID'],
				    'privilegeID' => $rolePrivilege['privilegeID']
			    ]
		    );
	    }
    }
}
